apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::812296538062:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::812296538062:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OPQ9VQGYFB7C
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-08T02:23:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4134"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d8110e93-386a-49ae-b6e5-787be80f1df4
